# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true

  - script: 'cd server && cmake . && make'
    displayName: 'CMake'

  - script: 'cd server/build && ./server'
    displayName: 'Run server'

  - task: CopyFiles@2
    displayName: 'Copy artifacts'
    inputs:
      contents: '**/server/build'
      targetFolder: '$(build.artifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      pathToPublish: '$(build.artifactStagingDirectory)'
      artifactName: 'artifact'
      artifactType: 'container'
